version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodes-app
    volumes:
      - ./output.log:/app/output.log
      - ./nodes:/app/nodes
      - ./example:/app/example
      - ./example/.well-known/acme-challenge:/app/.well-known/acme-challenge  # Mount ACME challenge folder
      - ./example/ssl:/app/example/ssl  # Mount folder for SSL certs inside app/example/ssl
    ports:
      - "8004:443"  # Prime HTTP(S)/2 
      - "8005:80"   # Proxy
    networks:
      - app-network
    # Override CMD in Dockerfile with my ENV variable
    command: sh -c "npm run example:prod:start"

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - app
    volumes:
      - ./example/.well-known/acme-challenge:/app/.well-known/acme-challenge  # ACME challenge folder
      - ./example/ssl:/etc/letsencrypt  # Mount SSL cert folder
    command: certonly --webroot --webroot-path=/app/.well-known/acme-challenge --email ${DOMAIN_EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN}  # Replace with your domain
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
