name: nodes.js Rlease

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    if: github.event_name == 'push' && github.event.head_commit.message matches /^[0-9]+\.[0-9]+\.[0-9]+$/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
